### ISSUE TITLE
Account is null

### ISSUE THREAD

**Issue by antonma** [geriremenyi/oanda-dotnet-sdk#25]
Hi,

I have this code and unfortunately I receive  null from this functions back. The interesting part ist that it worked for some request and then stopped. Also if I create a new sub accounts it would work one time and then I would get nulls again. Any idea what could be the reason?

```
 Configuration config = new Configuration();
            config.BasePath = "https://api-fxpractice.oanda.com/v3";            
            config.AccessToken = _Token;
            
            var apiInstance = new AccountApi(config);                                    
            AccountResponse accountResponse = await apiInstance.GetAccountAsync(_SubAccountID);
 ```

accountResponse  is null 

Thank you,
Anton

**Comment by geriremenyi** [comment]
It looks like you are pretty much using the [generated client](https://github.com/geriremenyi/oanda-dotnet-client) directly. I haven't looked into it so not sure what could be the problem there, but please consider to open an issue there and/or try the SDK directly as described [here](https://github.com/geriremenyi/oanda-dotnet-sdk/blob/develop/README.md). The SDK might be limited though as the project was parked in a half ready state. A big refactor is coming in the following months after I'm done with the base of the rework through the pipeline.

**Comment by antonma** [comment]
Hi,

thank you very much for your feedback and I really appreciate it. If I try it like this I get the same issue

```
 var token = "XXXXXXXXXXXXXXXXXXXXXXX-4d6335e5ac79d3e9dcf4f951e7b4620d";
            string accountID = "XXXXXXXXXXXXXX";
            var server = OandaConnectionType.FxPractice;

            var connection = new OandaApiConnectionFactory().CreateConnection(server, token);
            var balance = connection.GetAccount(accountID).GetDetails().Balance;
```

Error
```
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at GeriRemenyi.Oanda.V20.Sdk.Account.Account.GetDetails() in D:\repos\oanda-dotnet-sdk-develop\oanda-dotnet-sdk-develop\src\GeriRemenyi.Oanda.V20.Sdk\Account\Account.cs:line 42
   at TestConsole.Program.Main(String[] args) in D:\repos\oanda-dotnet-sdk-develop\oanda-dotnet-sdk-develop\src\TestConsole\Program.cs:line 16
```

![image](https://user-images.githubusercontent.com/13572239/154338205-ac99077e-599a-4e32-8c8c-b31b3b85e2b8.png)

**Comment by antonma** [comment]
OK, I found the issue.

![image](https://user-images.githubusercontent.com/13572239/154363095-9a96d790-4522-4486-a508-36be1dcd2d0e.png)

So basically I manually opened a NAS trade and since then I was not able to get the account information until I closed the NAS trade...

**Comment by geriremenyi** [comment]
Thanks for investigating. Good catch.

Will be working on to handle all types of instruments and also add null safety.

**Comment by antonma** [comment]
Awesome. 
Thank you for this sdk!
